"use client"

import { useState } from "react"
import Link from "next/link"
import Image from "next/image"

import { Linkedin, Youtube } from "lucide-react"

interface FooterContent {
    tagline: string
    copyright: string
  }
  
  const defaultContent: FooterContent = {
    tagline: "Personal website by usri yusron that generated by V0.app and Aceternity UI",
    copyright: "© 2025 — Muhamad Usri Yusron",
  }
  

export function Footer() {
  const [content] = useState<FooterContent>(defaultContent);

    const links = [
      { href: "/", label: "Home"},
      { href: "#skill", label: "Skill"},
      { href: "#project", label: "Project"},
      // { href: "faq", label: "FAQ", icon: HelpCircle },
      { href: "#certificate", label: "Certificate"},
      { href: "#blog", label: "Blog"},
    ]
    
    return(
        <footer className="border-t border-white/10 pb-20 md:pb-10">
        <div className="container mx-auto px-4 py-10">
          <div className="grid gap-8 md:grid-cols-[1.2fr_1fr_1fr]">
            {/* Brand */}
            <div className="space-y-3">
              <div className="flex items-center gap-1.5">
                <Image src="/icons/skitbit-white.svg" alt="Skitbit logo" width={24} height={24} className="h-6 w-6" />
                <span className="text-xl font-semibold text-lime-300">Usri.Yusron</span>
              </div>
              <p className="max-w-sm text-sm text-neutral-400">{content.tagline}</p>
            </div>

            {/* Navigation */}
            <div className="grid grid-cols-2 gap-6 sm:grid-cols-3 md:grid-cols-2">
              <div>
                <h5 className="mb-2 text-xs font-semibold uppercase tracking-widest text-neutral-400">Navigation</h5>
                <ul className="space-y-2 text-sm text-neutral-300">
                  {links.map((l) => (
                    <li key={l.href}>
                      <Link href={l.href} className="hover:text-lime-300">
                        {l.label}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <h5 className="mb-2 text-xs font-semibold uppercase tracking-widest text-neutral-400">Social media</h5>
                <ul className="space-y-2 text-sm text-neutral-300">
                  <li className="flex items-center gap-2">
                    <Linkedin className="h-4 w-4 text-neutral-400" />
                    <a
                      href="https://www.linkedin.com/in/muhamad-usriyusron/"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="hover:text-lime-300"
                      aria-label="Follow skitbit on Twitter"
                    >
                      Linkedin
                    </a>
                  </li>
                  <li className="flex items-center gap-2">
                    <Youtube className="h-4 w-4 text-neutral-400" />
                    <a
                      href="https://www.youtube.com/@programmer-cupu-v1"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="hover:text-lime-300"
                      aria-label="Subscribe to skitbit on YouTube"
                    >
                      YouTube
                    </a>
                  </li>
                  <li className="flex items-center gap-2">
                    <a
                      href="https://www.instagram.com/usri.yusron/"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="hover:text-lime-300"
                      aria-label="Follow skitbit on Instagram"
                    >
                      Instagram
                    </a>
                  </li>
                  <li className="flex items-center gap-2">
                    <a
                      href="https://wa.me/6283827406460"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="hover:text-lime-300"
                      aria-label="Follow skitbit on Threads"
                    >
                      WhatsApp
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          {/* Bottom bar */}
          <div className="mt-8 flex flex-col items-center justify-between gap-4 border-t border-white/10 pt-6 text-xs text-neutral-500 sm:flex-row">
            <p>{content.copyright}</p>
            <div className="flex items-center gap-6">
              <Link href="/" className="hover:text-lime-300">
                Revision Policy
              </Link>
              <Link href="/" className="hover:text-lime-300">
                Terms & Conditions
              </Link>
            </div>
          </div>
        </div>
      </footer>
    )
}